sudo: required
services:
  - docker

before_install:
  - docker build -t oklamos/react-web -f Dockerfile.dev .

scripts:
  - docker run -e CI=true oklamos/react-web npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-web-test"
  env: "Dockerwebtest-env"
  bucket_name: "elasticbeanstalk-us-east-1-098305039979"
  bucket_path: "docker-web-test"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
